# This workflow runs tests on Ubuntu with all supported Python versions
# using a MariaDB service container

name: Ubuntu Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 12345:3306
        env:
          MYSQL_ROOT_PASSWORD: 'RootPassphrase' # password for root account
          MYSQL_DATABASE: 'exoskeleton' # database to be created on image startup
          MYSQL_USER: 'exoskeleton' # User with all right for exoskeleton database
          MYSQL_PASSWORD: 'exoskeleton' # Password for the exoskelton user

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        pip install -r requirements.txt

    - name: Install test utilities
      run: |
        pip install pytest pytest_mock pyfakefs

    - name: Install Chromium
      run: sudo apt install chromium-browser

    # The next step need to wait until the MariaDB container is ready.
    # This pings it until it gets an answer:
    - name: Wait for MariaDB to initialize
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"12345" --silent; do
          sleep 1
        done

    - name: Fill exoskeleton database
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        mysql --host='127.0.0.1' -P"$PORT" --user='root' --password='RootPassphrase' exoskeleton < 'Database-Scripts/Generate-Database-Schema-MariaDB.sql'

    - name: Make a directory to store downloads
      run: mkdir ./fileDownloads

    - name: Run tests without side-effects
      run: pytest tests/tests_without_side_effects.py

    - name: Run system-test with pytest
      run: pytest tests/tests_with_side_effects.py

    - name: List downloaded files
      run: ls -l ./fileDownloads
